import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadSeoDataModule, PROJECT_ROOT } from "./seo-data-loader.mjs";

const PUBLIC_DIR = path.join(PROJECT_ROOT, "public");

function escapeXml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function isIndexable(descriptor) {
  return !descriptor.robots?.toLowerCase().includes("noindex");
}

function renderSitemap(urls) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Generated by scripts/generate-sitemap.mjs. Do not edit by hand. -->",
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...urls.map((url) => `  <url>\n    <loc>${escapeXml(url)}</loc>\n  </url>`),
    "</urlset>",
    "",
  ].join("\n");
}

function renderRobotsTxt(siteUrl) {
  return [
    "# Generated by scripts/generate-sitemap.mjs. Do not edit by hand.",
    "User-agent: *",
    "Allow: /",
    "",
    `Sitemap: ${siteUrl}/sitemap.xml`,
    "",
  ].join("\n");
}

async function main() {
  const { mod, cleanup } = await loadSeoDataModule("ng-sitemap-");

  try {
    const siteUrl = mod.normalizeSiteUrl(
      process.env.VITE_SITE_URL || mod.DEFAULT_SITE_URL,
    );

    const uniqueUrls = new Map();

    for (const route of mod.getSeoPrerenderRoutes(siteUrl)) {
      if (!isIndexable(route.descriptor)) continue;

      uniqueUrls.set(
        mod.absoluteUrl(route.descriptor.canonicalPath, siteUrl),
        true,
      );
    }

    const urls = [...uniqueUrls.keys()];

    await mkdir(PUBLIC_DIR, { recursive: true });
    await Promise.all([
      writeFile(path.join(PUBLIC_DIR, "sitemap.xml"), renderSitemap(urls), "utf8"),
      writeFile(path.join(PUBLIC_DIR, "robots.txt"), renderRobotsTxt(siteUrl), "utf8"),
    ]);

    console.log(`Generated sitemap.xml and robots.txt for ${urls.length} URLs.`);
  } finally {
    await cleanup();
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
